ProcessManagement/Controllers/ApplicationController.cs
using ProcessManagement.Cache;
using ProcessManagement.Core;
using ProcessManagementModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ProcessManagement.Controllers
{
    public class ApplicationController : CookieController
    {
        public int UserAuthenticatedId => User.Identity.IsAuthenticated ? Convert.ToInt32(User.Identity.Name) : 0;

        public Users UserAuthenticated => Core.User.GetUserById(UserAuthenticatedId);

        public AccessGroup AccessGroupUser => UserAuthenticated.AccessGroup;

        public bool IsApprover => AccessGroupUser.Approver;

        public enum StateModal
        {
            Success,
            Danger,
            Warning,
            Info
        };

        [ChildActionOnly]
        public ActionResult TempMessage()
        {
            return PartialView("CommonModals");
        }

        public async Task SendRegisterEmail(string sendEmail, string name, string subject, string password, string userName, DTO.ModelsView.AccessGroup accessGroup)
        {
            var email = new Core.Email();
            await email.SendRegisterEmail(sendEmail, name, subject, password, userName, accessGroup);
        }

        public void SetCheckUser()
        {
            HttpContext.Session?.Add("UserId", UserAuthenticated.Id);
            HttpContext.Session?.Add("UserName", UserAuthenticated.UserName);
            HttpContext.Session?.Add("Name", UserAuthenticated.Name);
            HttpContext.Session?.Add("ProfileImageId", UserAuthenticated.ProfileImageId.HasValue ? UserAuthenticated.ProfileImageId.Value : 0);
            HttpContext.Session?.Add("ClientDisplayName", UserAuthenticated.AccessGroup.Clients.DisplayName);
            HttpContext.Session?.Add("ProfileContent", Convert.ToBase64String(UserAuthenticated.ProfileImageId.HasValue ? UserAuthenticated.Images.Content : new byte[0]));
        }

        public void LogOutSessionUser()
        {
            HttpContext.Session["UserId"] = null;
            HttpContext.Session["UserName"] = null;
            HttpContext.Session["Name"] = null;
            HttpContext.Session["ProfileImageId"] = null;
            HttpContext.Session["ClientDisplayName"] = null;
        }

        public void LoadMenu()
        {
            ViewBag.Menu = CacheManager.GetMenu(AccessGroupUser.Id);
        }

        public void OpenModal(StateModal stateModal, string title, string text)
        {
            TempData["StateModal"] = stateModal;
            TempData["TitleModal"] = title;
            TempData["TextModal"] = text;
        }

        [HttpPost]
        public JsonResult Dropzone(string guid)
        {
            try
            {
                if (!string.IsNullOrEmpty(guid))
                {
                    if (!CacheManager._cacheImagesAtachment.Any(x => x.Key.Equals(guid)))
                        CacheManager._cacheImagesAtachment.Add(guid, new List<ProcessManagementModel.Images>());

                    for (var i = 0; i < Request.Files.Count; i++)
                    {
                        var file = Request.Files.Get(i);
                        CacheManager._cacheImagesAtachment[guid].Add(RequestFileToImages(file));
                    }
                }

                return Json(new { guid = guid });
            }
            catch (Exception ex)
            {
                return Json(new { messageError = ex.Message + " - " + ex.InnerException });
            }
        }

        public void DropzoneFromController(List<Images> images, string guid)
        {
            if (!string.IsNullOrEmpty(guid))
            {
                if (!CacheManager._cacheImagesAtachment.Any(x => x.Key.Equals(guid)))
                    CacheManager._cacheImagesAtachment.Add(guid, new List<ProcessManagementModel.Images>());

                foreach (var image in images)
                    if (!CacheManager._cacheImagesAtachment[guid].Any(x => x.Content.Equals(image.ContentType)))
                        CacheManager._cacheImagesAtachment[guid].Add(image);
            }
        }

        private ProcessManagementModel.Images RequestFileToImages(HttpPostedFileBase file)
        {
            var image = new ProcessManagementModel.Images();

            image.Name = Path.GetFileName(file.FileName);
            image.ContentType = file.ContentType;

            using (var reader = new BinaryReader(file.InputStream))
                image.Content = reader.ReadBytes(file.ContentLength);

            return image;
        }

        [HttpPost]
        public JsonResult RemoveFileFromCache(string guid, string fileName)
        {
            try
            {
                if (!string.IsNullOrEmpty(guid) && !string.IsNullOrEmpty(fileName))
                {
                    if (CacheManager._cacheImagesAtachment.Any(c => c.Key.Equals(guid)))
                    {
                        var cache = new List<ProcessManagementModel.Images>();
                        cache = CacheManager._cacheImagesAtachment[guid].Where(x => x.Name.Equals(fileName)).ToList();

                        foreach (var file in cache)
                            CacheManager._cacheImagesAtachment[guid].Remove(file);
                    }
                }

                return Json(new { message = "Success" });
            }
            catch (Exception ex)
            {
                return Json(new { messageError = ex.Message + " - " + ex.InnerException });
            }
        }

        public List<ProcessManagementModel.Images> GetImagesByGuid(string guid)
        {
            var images = new List<ProcessManagementModel.Images>();

            if (CacheManager._cacheImagesAtachment.Any(c => c.Key.Equals(guid)))
                images = CacheManager._cacheImagesAtachment[guid];

            return images;
        }

        public List<SelectListItem> UnionSelectList(SelectList selectList)
        {
            var all = new Dictionary<int, string>() { { 0, "Todos" } };
            var selectListWithFieldAll = new SelectList(all, "Key", "Value", 0);

            return selectListWithFieldAll.Union(selectList).ToList();
        }

        public string SuitSize(string value, char character, int length, bool left)
        {
            if (value.Length < length)
            {
                while (value.Length < length)
                {
                    if (left)
                        value = $"{character}{value}";
                    else
                        value = $"{value}{character}";
                }
            }
            else if (value.Length > length)
            {
                if (left)
                    value = value.Substring(0, length);
                else
                    value = value.Substring(value.Length - length, length);
            }

            return value.ToUpper();
        }

        public string GetNameMonth(string month)
        {
            switch (month)
            {
                case "1":
                    return "Janeiro";

                case "2":
                    return "Fevereiro";

                case "3":
                    return "Marco";

                case "4":
                    return "Abril";

                case "5":
                    return "Maio";

                case "6":
                    return "Junho";

                case "7":
                    return "Julho";

                case "8":
                    return "Agosto";

                case "9":
                    return "Setembro";

                case "10":
                    return "Outubro";

                case "11":
                    return "Novembro";

                case "12":
                    return "Dezembro";

                default:
                    return "";
            }
        }
    }
}

ProcessManagement/Controllers/ImageController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace ProcessManagement.Controllers
{
    public class ImageController : ApplicationController
    {
        public async Task<ActionResult> Index(int id)
        {
            var image = Core.Image.GetById(id);

            return File(image.Content, image.ContentType);
        }
    }
}

ProcessManagement/Views/User/AlterPassword.cshtml
@model ProcessManagement.DTO.ModelsView.AlterPassword
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

@using (Html.BeginForm("AlterPassword", "User", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="page-header">
        <h1 class="col-xs-12 col-sm-4 text-center text-left-sm"><i class="fa fa-gears page-header-icon"></i>&nbsp;&nbsp;Alterar senha</h1>
    </div>

    <div class="panel-heading">
        <span class="panel-title">Digite as informações</span>
        <div class="panel-heading-controls">
            <div class="panel-heading-icon"><i class="fa fa-th"></i></div>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-12 hide">
                @Html.LabelFor(model => model.UserId)
                @Html.TextBoxFor(model => model.UserId, new { @class = "form-control" })
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                @Html.LabelFor(model => model.Password)
                @Html.PasswordFor(model => model.Password, new { @class = "form-control" })
                <div for="Description" class="jquery-validate-error help-block">
                    @Html.ValidationMessageFor(model => model.Password, string.Empty, new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                @Html.LabelFor(model => model.NewPassword)
                @Html.PasswordFor(model => model.NewPassword, new { @class = "form-control" })
                <div for="Description" class="jquery-validate-error help-block">
                    @Html.ValidationMessageFor(model => model.NewPassword, string.Empty, new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                @Html.LabelFor(model => model.ConfirmPassword)
                @Html.PasswordFor(model => model.ConfirmPassword, new { @class = "form-control" })
                <div for="Description" class="jquery-validate-error help-block">
                    @Html.ValidationMessageFor(model => model.ConfirmPassword, string.Empty, new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>

    <div class="panel-footer ">
        <div class="text-right">
            <a href="javascript:history.back()" class="btn btn-labeled btn-danger" style="margin-top:25px !important"><span class="btn-label icon fa  fa-arrow-circle-left"></span>Voltar</a>
            <button type="submit" class="btn btn-labeled btn-primary" style="margin-top:25px !important"><span class="btn-label icon fa fa-check-circle-o"></span>Salvar</button>
        </div>
    </div>
}

ProcessManagement/Views/User/CreateAccessGroup.cshtml
@model ProcessManagement.DTO.ModelsView.AccessGroup
@using ProcessManagement.Controllers
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

<div class="page-header">
    <h1 class="col-xs-12 col-sm-4 text-center text-left-sm"><i class="fa fa-users page-header-icon"></i>&nbsp;&nbsp;Cadastro de grupo de acesso</h1>
</div>

<div class="panel">
    <div class="panel-heading">
        <span class="panel-title">Digite as informações</span>
        <div class="panel-heading-controls">
            <div class="panel-heading-icon"><i class="fa fa-th"></i></div>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-12 hide">
                @Html.LabelFor(model => model.Id)
                @Html.TextBoxFor(model => model.Id, new { @class = "form-control" })
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                @Html.LabelFor(model => model.Name)
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                <div for="Description" class="jquery-validate-error help-block">
                    @Html.ValidationMessageFor(model => model.Name, string.Empty, new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
</div>

<div class="panel">
    <div class="panel-heading">
        <span class="panel-title">Tem acesso aos menus:</span>
        <div class="panel-heading-controls">
            <div class="panel-heading-icon"><i class="fa fa-sitemap"></i></div>
        </div>
    </div>
    <div class="panel-body Menus">
        <div class="row">
            <div class="col-sm-12">
                @{
                    foreach (var menuItem in (List<ProcessManagement.DTO.ModelsView.Menu>)ViewBag.Menu)
                    {
                        if (menuItem.Menu_Childs.Count > 0)
                        {
                            <label class="checkbox-inline" style="padding-left: 0px;">
                                <i class="@menuItem.Icon"></i>
                                <span class="lbl">@menuItem.Text</span>
                            </label>
                            <br /><br />

                            foreach (var menuItemChild in menuItem.Menu_Childs)
                            {
                                <label class="checkbox-inline" style="margin-left: 2em;">
                                    <input type="checkbox" class="px" value="@menuItemChild.Id.ToString()">
                                    <span class="lbl">@menuItemChild.Text</span>
                                </label>
                                <br /><br />
                            }
                        }
                        else
                        {
                            <label class="checkbox-inline">
                                <input type="checkbox" class="px" value="@menuItem.Id.ToString()">
                                <span class="lbl">@menuItem.Text</span>
                            </label>
                            <br /><br />
                        }
                    }
                }
            </div>
        </div>
    </div>
</div>

<div class="panel">
    <div class="panel-heading">
        <span class="panel-title">Visualiza as informações de:</span>
        <div class="panel-heading-controls">
            <div class="panel-heading-icon"><i class="fa fa-tags"></i></div>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-12">
                <label class="checkbox-inline">
                    <input type="checkbox" class="px" checked="checked" id="myData">
                    <span class="lbl">Apenas dados próprios</span>
                </label>
            </div>
        </div>
        <br />
        <div class="row">
            <div class="col-sm-12 permissions">
                <label class="checkbox-inline">
                    <input type="checkbox" class="px selectedMenu" id="myGroup" value="0" disabled>
                    <span class="lbl">Próprio grupo</span>
                </label>
            </div>
        </div>
        <br />

        @{
            foreach (var tableValue in (List<ProcessManagement.DTO.ModelsView.AccessGroup>)ViewBag.AccessGroups)
            {
                <div class="row">
                    <div class="col-sm-12 permissions">
                        <label class="checkbox-inline">
                            <input type="checkbox" class="px selectedMenu" id="@tableValue.Id" value="@tableValue.Id" disabled>
                            <span class="lbl">@tableValue.Name</span>
                        </label>
                    </div>
                </div>
                <br />
            }
        }
    </div>
</div>

<div class="panel">
    <div class="panel-heading">
        <span class="panel-title">Autoridade</span>
        <div class="panel-heading-controls">
            <div class="panel-heading-icon"><i class="fa fa-gavel"></i></div>
        </div>
    </div>
    <div class="panel-body">
        <label class="checkbox-inline">
            <input type="checkbox" class="px" value="1" id="authority" disabled>
            <span class="lbl">Atribui responsabilidade</span>
        </label>
        <br /><br />
        <label class="checkbox-inline">
            <input type="checkbox" class="px" value="0" id="approver" disabled>
            <span class="lbl">Aprovador</span>
        </label>
    </div>
</div>

<div class="panel-footer text-right">
    <a href="javascript:history.back()" class="btn btn-labeled btn-danger" style="margin-top:25px !important"><span class="btn-label icon fa  fa-arrow-circle-left"></span>Voltar</a>
    <button type="submit" class="btn btn-labeled btn-primary" style="margin-top:25px !important" onclick="SaveAccessGroup()"><span class="btn-label icon fa fa-check-circle-o"></span>Salvar</button>
</div>

<script>
    $("#myData").change(function () {
        if ($(this).is(":checked")) {
            $(".selectedMenu").prop("disabled", true);
            $(".selectedMenu").prop("checked", false);

            $("#authority").prop("disabled", true);
            $("#approver").prop("disabled", true);
        }
        else {
            $(".selectedMenu").prop("disabled", false);

            $("#authority").prop("disabled", false);
            $("#approver").prop("disabled", false);
        }
    });

    function SaveAccessGroup() {
        var menus = new Object();
        var permission = [];
        var authority = false;
        var approver = false;
        var name = $("#Name").val();
        var id = 0;

        $('.Menus input[type=checkbox]').each(function () {
            menus[this.value] = this.checked;
        });

        var jMenus = JSON2.stringify(menus);

        if ($("#myData").is(":checked")) {
            $('.permissions input[type=checkbox]').each(function () {
                if (this.checked) {
                    permission.push(this.value);
                }
            });
        }

        if ($("#authority").is(":checked")) {
            authority = true;
        }

        if ($("#approver").is(":checked")) {
            approver = true;
        }

        $.ajax({
            type: "POST",
            url: '@Url.Action("SaveAccessGroup", "User")',
            data: { 'accessGroupId': id, 'accessGroupName': name, 'jMenus': jMenus, 'permission': permission, 'authority': authority, 'approver': approver },
            dataType: "json",
            success: function (response) {
                if (response != null && response.success) {
                    @{ var typeSuccess = (int)ApplicationController.StateModal.Success; };

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("OpenModal", "Application")',
                        data: { 'stateModal': @typeSuccess, 'title': 'Sucesso', 'text': response.responseText },
                        dataType: "json",
                        success: function (response) {
                        },
                        error: function (response) {
                        }
                    });
                } else {
                    @{ var typeWarning = (int)ApplicationController.StateModal.Warning; };

                    $.ajax({
                        type: "POST",
                        url: '@Url.Action("OpenModal", "Application")',
                        data: { 'stateModal': @typeWarning, 'title': 'Atenção', 'text': response.responseText },
                        dataType: "json",
                        success: function (response) {
                        },
                        error: function (response) {
                        }
                    });
                }

                location.href = '@Url.Action("AccessGroup", "User")';
            },
            error: function (response) {
                @{ var typeDanger = (int)ApplicationController.StateModal.Danger; };

                $.ajax({
                    type: "POST",
                    url: '@Url.Action("OpenModal", "Application")',
                    data: { 'stateModal': @typeDanger, 'title': 'Erro', 'text': response.responseText },
                    dataType: "json",
                    success: function (response) {
                    },
                    error: function (response) {
                    }
                });

                location.href = '@Url.Action("AccessGroup", "User")';
            }
        });
    };
</script>

ProcessManagement/Views/User/CreateUser.cshtml
@model ProcessManagement.DTO.ModelsView.User
@{ Layout = "~/Views/Shared/_Layout.cshtml"; }

<div class="page-header">
    <h1 class="col-xs-12 col-sm-4 text-center text-left-sm"><i class="fa fa-user page-header-icon"></i>&nbsp;&nbsp;Novo usuário</h1>
</div>

@using (Html.BeginForm("CreateUser", "User", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="panel-heading">
        <span class="panel-title">Digite as informações</span>
        <div class="panel-heading-controls">
            <div class="panel-heading-icon"><i class="fa fa-th"></i></div>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-12 hide">
                @Html.LabelFor(model => model.Id)
                @Html.TextBoxFor(model => model.Id, new { @class = "form-control" })
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <label for="AccessGroupId">Grupo de acesso</label>
                @Html.DropDownList("AccessGroupId", null, new { @class = "form-control" })
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                @Html.LabelFor(model => model.Name)
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
                <div for="Description" class="jquery-validate-error help-block">
                    @Html.ValidationMessageFor(model => model.Name, string.Empty, new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-6">
                @Html.LabelFor(model => model.UserName)
                @Html.TextBoxFor(model => model.UserName, new { @class = "form-control" })
                <div for="Description" class="jquery-validate-error help-block">
                    @Html.ValidationMessageFor(model => model.UserName, string.Empty, new { @class = "text-danger" })
                </div>
            </div>
            <div class="col-sm-6">
                @Html.LabelFor(model => model.Email)
                @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })
                <div for="Description" class="jquery-validate-error help-block">
                    @Html.ValidationMessageFor(model => model.Email, string.Empty, new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                @if ((ViewBag.IsEdit != null && ViewBag.IsEdit == true))
                {
                    <button onclick="location.href='@Url.Action("AlterPassword", "User", new { id = Model.Id })'" type="button" class="btn btn-labeled btn-warning"><span class="btn-label icon fa fa-pencil-square-o"></span>Alterar Senha</button>
                }
            </div>
        </div>
    </div>
    <br />

    <div class="panel-heading">
        <span class="panel-title">Imagem</span>
        <div class="panel-heading-controls">
            <div class="panel-heading-icon"><i class="fa fa-paperclip"></i></div>
        </div>
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-12">
                <div id="dropzoneAtachmentImage" class="dropzone-box">
                    <div class="dz-default dz-message">
                        <i class="fa fa-download"></i>
                        Drop file in here<br><span class="dz-text-small">or click to pick manually</span>
                    </div>
                    <div class="fallback">
                        <input name="file" type="file" multiple />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="panel-footer ">
        <div class="text-right">
            <a href="javascript:history.back()" class="btn btn-labeled btn-danger" style="margin-top:25px !important"><span class="btn-label icon fa  fa-arrow-circle-left"></span>Voltar</a>
            <button type="submit" class="btn btn-labeled btn-primary" style="margin-top:25px !important"><span class="btn-label icon fa fa-check-circle-o"></span>Salvar</button>
        </div>
    </div>

    <input class="form-control hidden" id="inputGuid" name="inputGuid" type="text" value="">
}

<script>
    $(document).ready(function () {
        @if (ViewBag.IsEdit != null && ViewBag.IsEdit == true)
        {
            @:prepareDropzoneEdit();
        }
        else
        {
            @:prepareDropzoneInsert();
        }
    });

    var guid = guid();

    function prepareDropzoneInsert() {
        $("#dropzoneAtachmentImage").dropzone({
            url: "@Url.Action("Dropzone", "Application")?guid=" + guid,
            paramName: "file",
            maxFilesize: 5.0,
            uploadMultiple: true,
            parallelUploads: 10000,
            maxFiles: 1,
            addRemoveLinks: true,
            dictResponseError: "Can't upload file!",
            acceptedFiles: "image/*",
            autoProcessQueue: true,
            success: function (data, response) {
                PixelAdmin.plugins.alerts.clear(true);
                if (response["messageError"] == null) {
                    $("#inputGuid").val(guid);
                } else {
                    PixelAdmin.plugins.alerts.add(response["messageError"], { type: "warning" });
                }
            },
            removedfile: function (file) {
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("RemoveFileFromCache", "Application")',
                    data: { guid: guid, fileName: file.name },
                    success: function (data, response) {
                        PixelAdmin.plugins.alerts.clear(true);
                        if (response["messageError"] != null) {
                            PixelAdmin.plugins.alerts.add(response["messageError"], { type: "warning" });
                        }
                    }
                });

                var _ref;
                return (_ref = file.previewElement) != null ? _ref.parentNode.removeChild(file.previewElement) : void 0;
            }
        });
    }

    function prepareDropzoneEdit() {
        $("#dropzoneAtachmentImage").dropzone({
            url: "@Url.Action("Dropzone", "Application")?guid=" + guid,
            paramName: "file",
            maxFilesize: 5.0,
            uploadMultiple: true,
            parallelUploads: 10000,
            maxFiles: 1,
            addRemoveLinks: true,
            dictResponseError: "Can't upload file!",
            acceptedFiles: "image/*",
            autoProcessQueue: true,
            success: function (data, response) {
                PixelAdmin.plugins.alerts.clear(true);
                if (response["messageError"] == null) {
                    $("#inputGuid").val(guid);
                } else {
                    PixelAdmin.plugins.alerts.add(response["messageError"], { type: "warning" });
                }
            },
            removedfile: function (file) {
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("RemoveFileFromCache", "Application")',
                    data: { guid: guid, fileName: file.name },
                    success: function (data, response) {
                        PixelAdmin.plugins.alerts.clear(true);
                        if (response["messageError"] != null) {
                            PixelAdmin.plugins.alerts.add(response["messageError"], { type: "warning" });
                        }
                    }
                });

                var _ref;
                return (_ref = file.previewElement) != null ? _ref.parentNode.removeChild(file.previewElement) : void 0;
            },
            init: function () {
                var thisDropzone = this;
                var id = $("#Id").val();

                $.ajax({
                    type: 'GET',
                    url: '@Url.Action("GetProfileImage", "User")',
                    data: { userId: id, guid: guid },
                    success: function (data, response) {
                        if (data) {
                            $.each(data.Data.Data, function (index, item) {
                                var mockFile = {
                                    name: item.Name,
                                    size: item.Size
                                };

                                var src = '@Url.Action("Index", "Image")?id=' + item.Id;

                                thisDropzone.emit("addedfile", mockFile);
                                thisDropzone.emit("thumbnail", mockFile, src);
                            });

                            $("#inputGuid").val(data.Data.Guid);
                            $("#dropzoneAtachmentImage img").css({ "max-width": "130px" });
                        }
                    }
                });
            }
        })
    }

    $("#AccessGroupId").select2({ placeholder: "Selecione o grupo de acesso" });
</script>